use assignment;
/*1*/
select FIRST_NAME AS WORKER_NAME from worker;

/*2*/
select upper(FIRST_NAME) AS FIRST_NAME from worker;

/*3*/
select distinct DEPARTMENT from worker;

/*4*/
select substring(FIRST_NAME,1,3) from worker;

/*5*/
select instr(FIRST_NAME,BINARY'a') from worker where FIRST_NAME='Amitabh';

/*6*/
select RTRIM(FIRST_NAME) from worker;

/*7*/
select LTRIM(DEPARTMENT) from worker;

/*8*/
select distinct length(DEPARTMENT) from worker;

/*9th */
SELECT REPLACE(FIRST_NAME,'a','A') FROM worker;

/*10th*/
SELECT CONCAT(FIRST_NAME," ",LAST_NAME) AS COMPLETE_NAME FROM worker;

/*11th*/
SELECT * FROM worker ORDER BY FIRST_NAME;

/*12*/
SELECT *FROM (SELECT * FROM WORKER ORDER BY FIRST_NAME)FNAME ORDER BY FNAME.DEPARTMENT DESC;

/*13*/
SELECT * FROM worker WHERE FIRST_NAME="VIPUL" OR FIRST_NAME="SATISH";

/*14*/
SELECT * FROM worker WHERE FIRST_NAME !="Vipul" AND FIRST_NAME !="Satish";

/*15*/
SELECT * FROM worker WHERE DEPARTMENT="Admin";

/*16*/
SELECT * FROM worker WHERE FIRST_NAME LIKE "a%";

/*17*/
SELECT * FROM worker WHERE FIRST_NAME LIKE "%a";

/*18*/
SELECT * FROM worker WHERE FIRST_NAME LIKE "%h" and length(FIRST_NAME)=6;

/*19*/
SELECT * FROM worker WHERE SALARY >=100000 AND SALARY<=500000;

/*20*/
SELECT * FROM worker WHERE JOINING_DATE LIKE "2014-02%";

/*21*/
SELECT COUNT(DEPARTMENT)FROM worker WHERE DEPARTMENT="Admin";

/*22*/
SELECT * FROM worker WHERE SALARY>=500000 OR SALARY<=100000;

/*23*/
SELECT COUNT(WORKER_ID),DEPARTMENT FROM worker GROUP BY DEPARTMENT ORDER BY DEPARTMENT DESC;

/*24*/
SELECT * FROM worker W,title T WHERE W.WORKER_ID=T.WORKER_REF_ID AND T.WORKER_TITLE="MANAGER";

/*25*/
SELECT * FROM title T,(SELECT COUNT(WORKER_REF_ID),WORKER_TITLE FROM TITLE GROUP BY WORKER_TITLE HAVING COUNT(WORKER_REF_ID)=1) W WHERE T.WORKER_TITLE=W.WORKER_TITLE;

/*26*/
SELECT * FROM worker WHERE MOD(WORKER_ID,2)<>0;

/*27*/
SELECT * FROM WORKER WHERE MOD(WORKER_ID,2)=0;

/*28*/
CREATE TABLE WORKER_CLONE SELECT * FROM worker;
SELECT * FROM WORKER_CLONE;

/*29*/
SELECT * FROM worker JOIN bonus ON WORKER.WORKER_ID=BONUS.WORKER_REF_ID;

/*30*/
SELECT * FROM worker WHERE WORKER_ID NOT IN(SELECT WORKER_REF_ID FROM bonus);




